In [30]:
import pandas as pd
import numpy as np



df_movies = pd.read_csv('/content/sample_data/User_Movie_Ratings.csv', index_col = 'User')

df_cars = pd.read_csv('/content/sample_data/carprices.csv', index_col = None)

buffet_data = pd.read_csv('/content/sample_data/Buffet_Details.csv')

In [31]:
df_movies[['Thor', 'Spiderman', 'Insidious']]

           Thor  Spiderman  Insidious
User
Arnold        6          6          1
Ben           9          8          8
Catherine    10          9          9
Disha         6          7          6
Euclid        7          3          7
Farhaan       6          9          4
Gaurav        8          9          7
Hilbert       6          8          1
Indira       10          9          8
Jason        10          9          4
Kenny         3          5          3
Lambert       5          4          9
Manish        7          6          5
Niti          3          2          5
Oliver        4          4          2
Pranav        8          8          7
Qader         8          8          5
Ravi          8          9         10
Sushant       5          6          5
Tavneet       1          4          5

In [33]:
display(df_cars.iloc[77])

car_ID                             78
symboling                           2
carname             mitsubishi lancer
doornumber                        two
carbody                     hatchback
enginelocation                  front
wheelbase                        93.7
carlength                       157.3
carwidth                         64.4
carheight                        50.8
curbweight                       1944
cylindernumber                   four
enginesize                         92
boreratio                        2.97
stroke                           3.23
compressionratio                  9.4
horsepower                         68
peakrpm                          5500
citympg                            31
highwaympg                         38
price                          6189.0
Name: 77, dtype: object

In [36]:
df_movies.loc[['Indira'], 'Annabelle']

User
Indira    6
Name: Annabelle, dtype: int64

In [40]:
df_movies.iloc[[12, 17], [0, 1, 2]]

        Thor  Justice League  Spiderman
User
Manish     7               6          6
Ravi       8               7          9

In [46]:
len(df_cars[(df_cars['carbody'] == 'convertible') & (df_cars['citympg'] > 20) & (df_cars['price'] < 15000)])

2